// Generated by CoffeeScript 1.6.2
(function() {
  var Director, Messenger, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Director = require("../concrete/director");

  Messenger = require("./messenger");

  module.exports = (function(_super) {
    __extends(_Class, _super);

    function _Class() {
      _ref = _Class.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    _Class.prototype.passive = true;

    /*
    */


    _Class.prototype._newMessenger = function(request, middleware) {
      return new Messenger(request, middleware, this);
    };

    return _Class;

  })(Director);

}).call(this);
