// Generated by CoffeeScript 1.6.2
(function() {
  var Messenger, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Messenger = require("../concrete/messenger");

  module.exports = (function(_super) {
    __extends(_Class, _super);

    function _Class() {
      _ref = _Class.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    _Class.prototype._next = function(middleware) {
      return middleware.listener.call(this, this.request.query, this);
    };

    /*
    	 ack on end
    */


    _Class.prototype._onEnd = function() {
      return this.response.end();
    };

    return _Class;

  })(Messenger);

}).call(this);
