// Generated by CoffeeScript 1.6.2
(function() {
  var LinkedQueue, Response, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  LinkedQueue = require("../collections/linkedQueue");

  Response = require("./response");

  _ = require("underscore");

  module.exports = (function(_super) {
    __extends(_Class, _super);

    /*
    	 constructor
    */


    function _Class(request, first, director) {
      var _this = this;

      this.request = request;
      this.first = first;
      this.director = director;
      this.request = this.request;
      this.router = director.router;
      this.from = request.from;
      _Class.__super__.constructor.call(this, first);
      this.response = new Response(this);
      this.response.reader().dump(function() {
        return _this.request.callback.apply(_this.request, arguments);
      }, this.request.headers);
    }

    /*
    */


    _Class.prototype.start = function() {
      return this.next();
    };

    /*
    */


    _Class.prototype.data = function(name) {
      var obj, _i, _len;

      if (arguments.length === 0) {
        return _.extend({}, this.request.sanitized, this.current.params, this.request.query);
      } else if (arguments.length > 1) {
        obj = {};
        for (_i = 0, _len = arguments.length; _i < _len; _i++) {
          name = arguments[_i];
          obj[name] = this.data(name);
        }
        obj;
      }
      return this.request.sanitized[name] || this.current.params[name] || (this.request.query ? this.request.query[name] : null);
    };

    /*
    	 flattens all param data into one object
    */


    _Class.prototype.flattenData = function(reset) {
      var allData, cur;

      if (this._allData && !reset) {
        return this._allData;
      }
      cur = this.current;
      allData = _.defaults(cur.params, this.request.query);
      cur = cur.getNextSibling();
      while (cur) {
        _.defaults(allData, cur.params);
        cur = cur.getNextSibling();
      }
      return this._allData = allData;
    };

    /*
    */


    _Class.prototype._onNext = function(middleware, args) {
      var e;

      if (args && args.length) {
        if (args[0]) {
          return _onError(args[0]);
        } else {
          _onNextData(args[1]);
        }
      }
      this.request.params = middleware.params;
      try {
        this.request.cache(this.hasNext);
        return this._next(middleware, args);
      } catch (_error) {
        e = _error;
        return this.response.error(e);
      }
    };

    /*
    */


    _Class.prototype._next = function(middleware) {
      return middleware.listener(this);
    };

    /*
    */


    _Class.prototype._onError = function(error) {};

    /*
    */


    _Class.prototype._onNextData = function() {};

    return _Class;

  })(LinkedQueue);

}).call(this);
