// Generated by CoffeeScript 1.6.2
(function() {
  var Reader, RequestReader, RequestWriter, Writer, outcome,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Reader = require("./io/reader");

  Writer = require("./io/writer");

  outcome = require("outcome");

  exports.Reader = RequestReader = (function(_super) {
    __extends(RequestReader, _super);

    /*
    	 constructor
    */


    function RequestReader(writer, from, path, query, sanitized, headers, filter, callback) {
      this.writer = writer;
      this.from = from;
      this.path = path;
      this.query = query;
      this.sanitized = sanitized != null ? sanitized : {};
      this.headers = headers != null ? headers : {};
      this.filter = filter != null ? filter : {};
      this.callback = callback != null ? callback : null;
      RequestReader.__super__.constructor.call(this, writer);
    }

    return RequestReader;

  })(Reader);

  exports.Writer = RequestWriter = (function(_super) {
    __extends(RequestWriter, _super);

    /*
    */


    function RequestWriter(_ops) {
      this._ops = _ops;
      this.next = _ops.next;
      this.pre = _ops.pre;
      this.path = _ops.path;
      this.type = _ops.type;
      this.from = _ops.from;
      this.query = _ops.query;
      this.filter = _ops.filter || {};
      this.headers = _ops.headers;
      this.callback = _ops.callback;
      this.sanitized = _ops.sanitized;
      RequestWriter.__super__.constructor.call(this);
    }

    /*
    */


    RequestWriter.prototype.reader = function() {
      return new RequestReader(this, this.from, this.path, this.query, this.sanitized, this.headers, this.filter, this.callback);
    };

    return RequestWriter;

  })(Writer);

  exports.Builder = (function() {
    /*
    */
    function _Class(router) {
      this.router = router;
      this.clean();
    }

    /*
    	 options which control how the request
    	 is handled. This can fill out the entire request vs using the methods given
    */


    _Class.prototype.options = function(value) {
      if (!arguments.length) {
        return this._ops;
      }
      this._ops = value || {};
      return this;
    };

    /*
    */


    _Class.prototype.clean = function() {
      this._ops = {};
      return this.from(this.router);
    };

    /*
    	 filterable tags
    	 DEPRECATED
    */


    _Class.prototype.tag = function(keyOrTags, value) {
      return this._objParam('filter', arguments, function(value) {
        if (typeof value === 'boolean') {
          return {
            $exists: value
          };
        }
        return value;
      });
    };

    _Class.prototype.filter = function(keyOrTag, value) {
      return this.tag(keyOrTag, value);
    };

    /*
    	 DEPRECATED
    */


    _Class.prototype.headers = function(value) {
      return this.header(value);
    };

    /*
    	 The header data explaining the request, such as tags, content type, etc.
    */


    _Class.prototype.header = function(keyOrHeaders, value) {
      return this._objParam('headers', arguments);
    };

    /*
    */


    _Class.prototype.type = function(value) {
      return this._param('type', arguments);
    };

    /*
    */


    _Class.prototype.from = function(value) {
      return this._param('from', arguments);
    };

    /*
    */


    _Class.prototype.to = function(value) {
      return this._param('to', arguments);
    };

    /*
    */


    _Class.prototype.path = function(value) {
      return this._param('path', arguments);
    };

    /* 
    	 Query would be something like ?name=craig&last=condon
    */


    _Class.prototype.query = function(value) {
      return this._param('query', arguments);
    };

    /* 
    	 data that has been cleaned up after validation
    */


    _Class.prototype.sanitized = function(value) {
      return this._param('sanitized', arguments);
    };

    /*
    	 response handler, or ack
    	 deprecated
    */


    _Class.prototype.response = function(callback) {
      return this._param('response', arguments);
    };

    /*
    	 on error callback
    */


    _Class.prototype.error = function(callback) {
      return this._param('error', arguments);
    };

    /*
    	 on success callback
    */


    _Class.prototype.success = function(callback) {
      return this._param('success', arguments);
    };

    /*
    	 append middleware to the end
    */


    _Class.prototype.next = function(middleware) {
      return this._param('next', arguments);
    };

    /*
    	 prepend middleware
    */


    _Class.prototype.pre = function(middleware) {
      return this._param('pre', arguments);
    };

    /*
    */


    _Class.prototype.dispatch = function(type) {
      var writer;

      this._ops.callback = outcome({
        error: this.error(),
        success: this.success(),
        callback: this.response()
      });
      if (type) {
        this.type(type);
      }
      writer = new RequestWriter(this._ops);
      this.router.dispatch(writer);
      return writer;
    };

    /*
    	 DEPRECATED
    */


    _Class.prototype.hasListeners = function() {
      return this.exists();
    };

    /*
    */


    _Class.prototype.exists = function() {
      return !!this.listeners().length;
    };

    /*
    */


    _Class.prototype.listeners = function() {
      return this.router.director(this.type()).getListeners({
        path: this._ops.path,
        filter: this._ops.filter
      }, false);
    };

    /*
    */


    _Class.prototype._param = function(name, args) {
      if (!args.length) {
        return this._ops[name];
      }
      this._ops[name] = args[0];
      return this;
    };

    /*
    */


    _Class.prototype._objParam = function(name, args, getValue) {
      var key, keyOrObj, value;

      if (!args.length) {
        return this._ops[name];
      }
      if (!this._ops[name]) {
        this._ops[name] = {};
      }
      keyOrObj = args[0];
      value = args[1];
      if (typeof keyOrObj === 'string') {
        if (args.length === 1) {
          return this._ops.headers[keyOrObj];
        }
        this._ops[name][keyOrObj] = getValue ? getValue(value) : value;
      } else {
        for (key in keyOrObj) {
          this._objParam(name, [key, keyOrObj[key]], getValue);
        }
      }
      return this;
    };

    return _Class;

  })();

}).call(this);
