// Generated by CoffeeScript 1.6.2
(function() {
  var LinkedList;

  module.exports = LinkedList = (function() {
    function LinkedList() {}

    /*
    */


    LinkedList.prototype.getNextSibling = function() {
      return this._nextSibling;
    };

    /*
    */


    LinkedList.prototype.addNextSibling = function(sibling, replNext) {
      if (!!this._nextSibling) {
        this._nexSibling._prevSibling = sibling;
      }
      sibling._prevSibling = this;
      if (!replNext) {
        sibling._nextSibling = this._nextSibling;
      }
      return this._nextSibling = sibling;
    };

    /*
    */


    LinkedList.prototype.getPrevSibling = function() {
      return this._prevSibling;
    };

    /*
    */


    LinkedList.prototype.addPrevSibling = function(sibling, replPrev) {
      if (!!this._prevSibling) {
        this._prevSibling._nextSibling = sibling;
      }
      sibling._nextSibling = this;
      if (!replPrev) {
        sibling._prevSibling = this._prevSibling;
      }
      return this._prevSibling = sibling;
    };

    /*
    */


    LinkedList.prototype.getFirstSibling = function() {
      var first;

      first = this;
      while (!!first._prevSibling) {
        first = first._prevSibling;
      }
      return first;
    };

    /*
    */


    LinkedList.prototype.getLastSibling = function() {
      var last;

      last = this;
      while (!!last._nextSibling) {
        last = last._nextSibling;
      }
      return last;
    };

    return LinkedList;

  })();

}).call(this);
