// Generated by CoffeeScript 1.6.2
(function() {
  var EventEmitter, LinkedQueue,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  module.exports = LinkedQueue = (function(_super) {
    __extends(LinkedQueue, _super);

    LinkedQueue.prototype.hasNext = true;

    /*
    	 moves into the next
    */


    function LinkedQueue(first, onNext) {
      this.first = first;
      LinkedQueue.__super__.constructor.call(this);
      this.last = first.getLastSibling();
      if (onNext) {
        this._onNext = onNext;
      }
    }

    /*
    	 moves onto the next request (middleware)
    */


    LinkedQueue.prototype.next = function() {
      if (!this.hasNext) {
        return false;
      }
      this._setNext();
      this._onNext(this.current, arguments);
      return true;
    };

    /*
    	 skips middleware
    */


    LinkedQueue.prototype.skipNext = function(count) {
      if (count == null) {
        count = 2;
      }
      if (!this.hasNext) {
        return false;
      }
      while ((count--) && this.hasNext) {
        this._setNext();
      }
      this._onNext(this.current);
      return true;
    };

    /*
    */


    LinkedQueue.prototype._setNext = function() {
      this.current = this.current ? this.current.getNextSibling() : this.first;
      this.hasNext = this.current.getNextSibling();
      if (!this.hasNext && !this.ended) {
        this.ended = true;
        return this._onEnd();
      }
    };

    /*
    */


    LinkedQueue.prototype._onNext = function(middleware) {};

    /*
    */


    LinkedQueue.prototype._onEnd = function() {};

    return LinkedQueue;

  })(EventEmitter);

  module.exports = LinkedQueue;

}).call(this);
