// Generated by CoffeeScript 1.6.2
(function() {
  var Director, outcome;

  Director = require("./director");

  outcome = require("outcome");

  module.exports = function(router) {
    var director;

    director = new Director("collect", router);
    return {
      name: director.name,
      director: director,
      router: {
        collect: function(path, query, headers, callback) {
          return this._pull(path, query, headers, callback, director.name);
        }
      },
      newListener: function(listener) {
        if (!!listener.route.tags.collect) {
          return router.request(listener.route.path).headers(listener.route.tags).success(listener.callback).collect();
        }
      },
      request: {
        collect: function(query, callback) {
          return this._pull(query, callback, director.name);
        }
      }
    };
  };

}).call(this);
